name = "nextjs-blog-template-worker"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

# KV namespaces for caching
[[kv_namespaces]]
binding = "CACHE"
id = "9cec3a566ea44544b2fc60ab9553d93c"

# Assets for static files
[assets]
directory = ".open-next/assets"

# Environment variables
[env.production]
NODE_ENV = "production"

[env.development]
NODE_ENV = "development"